site_name: NeuroPython workshop 2024
site_url: https://navis-org.github.io/neuropython2024/
site_description: Documentation and Materials for the NeuroPython workshop 2024
# strict: true

repo_name: navis-org/neuropython2024
repo_url: https://github.com/navis-org/neuropython2024
edit_uri: edit/main/docs/

nav:
  - Home: index.md

theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - content.code.copy
  #logo: images/icon.png
  # below option would prevents loading typefaces from Google Fonts
  # but see also the privacy plugin below
  #font: false
  icon:
    #logo: fontawesome/solid/eye
    repo: fontawesome/brands/github
  #favicon: images/icon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/regular/lightbulb
        name: "Switch to dark mode"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: fontawesome/solid/lightbulb
        name: "Switch to light mode"

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: "#"

plugins:
  # the privacy plugin will bundle external assets (like Google Fonts)
  # this should make the website GDPR compliant
  - privacy
  # the social plugin generates social cards for each page of the project
  # which are used as previews when sharing links to the documentation
  - social
  - section-index
  - search:
      separator: '[\s\-\_,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - autorefs
  #- literate-nav
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      # css_files:
      #   - stylesheets/extra.css
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            show_root_heading: true # default is false
            docstring_style: "numpy"
            line_length: 50 # default is 60
            # show_if_no_docstring: true # default is false
            # show_signature: false  # default is true
            show_signature_annotations: true # default is false
            annotations_path: "source" # default is 'brief'
            show_bases: false # default is true
            show_source: false # default is true
            docstring_section_style: "spacy" # default is "table" but the tables end up being too wide
  - glightbox

extra_css:
 - stylesheets/extra.css